name: NodeLint


on: [push]


jobs:
 build:


   runs-on: ubuntu-latest


   steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.9
      uses: actions/setup-node@v1
      with:
        node-version: 12.9
    - name: Install dependencies
      run: npm install
    - name: Lint
      run: npm run lint
